# -*- coding: utf-8 -*-
"""Fake data gen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17wrWwj12w6s-N2XkfLt9PBOpBt-GUvDF
"""

!pip install faker

import pandas as pd
import random
from faker import Faker
from datetime import datetime

fake = Faker()
random.seed(42)

n_employes = 50
postes = ['Data Analyst', 'Comptable', 'RH', 'Développeur']
bus = ['Bordeaux', 'Paris', 'Lyon']

# Génération des employés
employes = []

for i in range(1, n_employes + 1):
    embauche = fake.date_between(start_date='-5y', end_date='-1y')
    if random.random() < 0.3:
        depart = fake.date_between(start_date=embauche, end_date='today')
        statut = "Sorti"
    else:
        depart = ""
        statut = "Actif"
    employes.append({
        'EmployeID': i,
        'Nom': fake.last_name(),
        'Sexe': random.choice(['M', 'F']),
        'Âge': random.randint(25, 60),
        'Poste': random.choice(postes),
        'BU': random.choice(bus),
        'DateEmbauche': embauche,
        'DateDépart': depart,
        'Salaire': random.randint(28000, 55000),
        'Statut': statut
    })

df_employes = pd.DataFrame(employes)

# Génération des absences
absences = []
mois_liste = pd.date_range("2024-01-01", "2024-12-01", freq='MS').strftime("%Y-%m").tolist()

for e in df_employes['EmployeID']:
    for mois in mois_liste:
        absences.append({
            'EmployeID': e,
            'Mois': mois,
            'JoursAbsence': random.randint(0, 5)
        })

df_absences = pd.DataFrame(absences)

# Sauvegarde des CSV
df_employes.to_csv("employes.csv", index=False)
df_absences.to_csv("absences.csv", index=False)

from google.colab import files
files.download("employes.csv")
files.download("absences.csv")